###### Database Properties  ###########################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-reddit-clone
    username: root
    password: admin
  sql:
    init:
      mode: always
  jpa:
    hibernate.ddl-auto: update
#    update, none
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: c5429a9634c826
    password: 9b42bcc1ab64fc
    protocol: smtp
    properties.smtp:
      auth : true
      starttls.enable: true
############## Mail Properties ###########################################
#spring.mail:
#  host:sandbox.smtp.mailtrap.io
#  port:25
#  username:c5429a9634c826
#  password:9b42bcc1ab64fc
#  protocol:smtp